// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brqrphkflhzhntmvrmlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJycXJwaGtmbGh6aG50bXZybWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODQ0NjksImV4cCI6MjA1OTI2MDQ2OX0.Pyx7JEBQtrydBXRZQRFX62eUczdgim9xuSco4O4-ATs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);